name: CodeChecker Analysis

on: [push, pull_request]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Prepare build
      run: |
        sudo apt-get remove --purge man-db
        sudo apt update && sudo apt install cppcheck
        mkdir -pv Build
        cd Build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Run CodeChecker analysis
      id:  codechecker
      uses: whisperity/codechecker-analysis-action@v1
      with:
        logfile: ${{ github.workspace }}/Build/compile_commands.json

    - name: upload results to CI
      uses: actions/upload-artifact@v4
      with:
        name: "CodeChecker Bug Reports"
        path: ${{ steps.codechecker.outputs.result-html-dir }}
      
